AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for

Parameters:
  Name:
    Description: Name of App
    Type: String
    Default: hello-world
  EnvironmentType:
    Description: Name of Environment Type. Example - prod, test
    Type: String
    Default: test
  Owner:
    Description: An owner's login or team
    Type: String
    AllowedPattern: ".+"
    Default: Platform
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  SecurityGroup:
    Type: "AWS::SSM::Parameter::Value<AWS::EC2::SecurityGroup::Id>"
    Default: "/CNS/resources/mgmt_sg"
  Subnets:
    Type: "AWS::SSM::Parameter::Value<List<AWS::EC2::Subnet::Id>>"
    Default: "/CNS/resources/subnets/mgmt/primary"
  VPCID:
    Type: "AWS::SSM::Parameter::Value<String>"
    Default: "/CNS/resources/vpc_id"
Resources:   # Add Resource here
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: !Ref LatestAmiId
        InstanceType: t2.micro
        IamInstanceProfile:
          # Arn: !GetAtt InstanceProfile.Arn
          Arn: !Sub "arn:aws:iam::${AWS::AccountId}:instance-profile/BootstrapDefaultInstanceProfile"
        SecurityGroupIds: 
          - !GetAtt SG.GroupId
          - !Ref SecurityGroup
      
  ASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      MinSize: '0'
      MaxSize: '2'
      DesiredCapacity: '1'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      VPCZoneIdentifier: !Ref Subnets
      MetricsCollection: 
        - Granularity: "1Minute"
      Tags:
        - Key: Name
          Value: !Ref Name
          PropagateAtLaunch: true
        - Key: Patch Group
          Value: Standalone
          PropagateAtLaunch: true
    UpdatePolicy: # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-updatepolicy.html
      AutoScalingScheduledAction:
        IgnoreUnmodifiedGroupSizeProperties: 'true'
      AutoScalingRollingUpdate:
        MinInstancesInService: 0
        MaxBatchSize: 1
        SuspendProcesses:
          - HealthCheck
          - ScheduledActions
          - AlarmNotification

  SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow https to SSM
      VpcId: !Ref VPCID
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 10.0.0.0/8

  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref Role


  # ScalingPolicyBasedOnCPU:
  #   Type: 'AWS::AutoScaling::ScalingPolicy'
  #   Properties:
  #     AutoScalingGroupName: !Ref myASG
  #     PolicyType: TargetTrackingScaling
  #     TargetTrackingConfiguration:
  #       PredefinedMetricSpecification:
  #         PredefinedMetricType: ASGAverageCPUUtilization
  #       TargetValue: 10
  #     EstimatedInstanceWarmup: 60

  # ScalingPolicyBasedOnALBRequest:
  #   Type: 'AWS::AutoScaling::ScalingPolicy'
  #   Properties:
  #     AutoScalingGroupName: !Ref myASG
  #     PolicyType: TargetTrackingScaling
  #     TargetTrackingConfiguration:
  #       PredefinedMetricSpecification:
  #         PredefinedMetricType: ALBRequestCountPerTarget
  #         # ResourceLabel: !Join 
  #         #   - '/' 
  #         #   - - !GetAtt myLoadBalancer.LoadBalancerFullName
  #         #     - !GetAtt myASG.TargetGroupFullName
  #       TargetValue: 5
  #     EstimatedInstanceWarmup: 60

  # Scaling based on a schedule
  # RecurringScheduledActionUp:
  #   Type: 'AWS::AutoScaling::ScheduledAction'
  #   Properties:
  #     AutoScalingGroupName: !Ref myASG
  #     DesiredCapacity: 2
  #     Recurrence: '0 8 * * *'

  # RecurringScheduledActionDown:
  #   Type: 'AWS::AutoScaling::ScheduledAction'
  #   Properties:
  #     AutoScalingGroupName: !Ref myASG
  #     DesiredCapacity: 1
  #     Recurrence: '0 20 * * *'
